addSbtPlugin("com.geirsson"        % "sbt-scalafmt"        % "1.5.1")
addSbtPlugin("io.get-coursier"     % "sbt-coursier"        % "1.0.3")
addSbtPlugin("org.wartremover"     % "sbt-wartremover"     % "2.3.7")
addSbtPlugin("com.github.tkawachi" % "sbt-doctest"         % "0.8.0")
addSbtPlugin("com.typesafe.sbt"    % "sbt-native-packager" % "1.3.3")
addSbtPlugin("com.tapad"           % "sbt-docker-compose"  % "1.0.34")
